# Generated by Django 5.0.7 on 2024-09-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_orderitem_options_orderitem_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ONGOING', 'ongoing'), ('DELIVERED', 'delivered'), ('CLOSED', 'closed'), ('REFUNDED', 'refunded')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ONGOING', 'ongoing'), ('DELIVERED', 'delivered'), ('CLOSED', 'closed')], default='PENDING', max_length=15),
        ),
    ]
